export default{
    menuData:[
        {
            name:'首页',
            path:'/admin/home',
            id:1,
        },
        {
            name:'设置',
            path:'/admin/setting',
            id:2,
        },
        {
            name:'用户管理',
            path:'/admin/user',
            id:3,
            children:[
                {
                    name:'用户添加',
                    path:'/admin/user/add',
                    id:30,
                },
                {
                    name:'管理员管理',
                    path:'/admin/user/root',
                    id:31,
                },
            ]
        },
        {
            name:'图标展示',
            path:'/echart',
            id:4,
            children:[
                {
                    name:'饼状图',
                    path:'/admin/echart/pie',
                    id:40,
                    children:[
                        {
                            name:'饼1',
                            path:'/admin/echart/pie/pie1',
                            id:401,
                        },
                        {
                            name:'饼2',
                            path:'/admin/echart/pie/pie2',
                            id:402,
                        },
                        {
                            name:'饼3',
                            path:'/admin/echart/pie/pie3',
                            id:403,
                        },
                    ]
                },
                {
                    name:'折线图',
                    path:'/admin/echart/line',
                    id:41,
                    children:[
                        {
                            name:'线线1',
                            path:'/admin/echart/line/line1',
                            id:411,
                        },
                        {
                            name:'线线2',
                            path:'/admin/echart/line/line2',
                            id:412,
                        },
                    ]
                },
            ]
        },
        {
            name:'商品管理',
            path:'/admin/goods',
            id:'5'
        },
    ]
}